codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch: no
    changes: no
