[package]
name = "dirty-debug"
description = "Quick and dirty debugging"
version = "0.1.0"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

edition = "2021"

homepage = "https://github.com/orium/dirty-debug"
repository = "https://github.com/orium/dirty-debug"
documentation = "https://docs.rs/dirty-debug"
readme = "README.md"

keywords = [
    "debug",
]

categories = [
    "development-tools",
]

license = "MPL-2.0"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
    "/release-notes.md",
]

[badges]
codecov = { repository = "orium/dirty-debug", branch = "main", service = "github" }

[features]
fatal-warnings = []

[dependencies]
once_cell = "1.15.0"
dashmap = "5.4.0"

[dev-dependencies]
rand = "0.8.1"
indoc = "1.0.7"
